version: '3.1'
services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smarttbot
    ports:
      - "5001:3306"
    volumes:
      - ./db/script_db.sql:/script_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    cap_add:
      - SYS_NICE
  app:
    build: ./app
    working_dir: "/home/app"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smarttbot
    volumes:
      - ./app:/home/app
    depends_on:
      db:
          condition: service_healthy